#!/usr/bin/env ruby
require 'open-uri'
require 'json'
require 'pry'
require 'awesome_print'

def main
  case
  when ARGV == ['--run']
    do_run_examples = true
  when ARGV.empty?
    # no-op
  else
    raise "Invalid command line arguments"
  end

  if api_token.empty?
    puts 'No semaphore token found'
    #initialise
    exit
  end

  @git_branch = git_current_branch #check current git branch


  if !@git_branch.empty?
    if project_id.nil?
      puts 'Unable to locate project on semaphore'
      exit
    end
    if branch_id.nil?
      puts 'Unable to locate branch on semaphore'
      exit
    end

    examples = failed_examples
    puts examples.join("\n")
    run_examples(examples) if do_run_examples
  else
    puts 'No git branch detected'
  end

end

def git_current_project
  `git remote -v`.lines.grep(/^origin\s/).first.scan(%r[github.com:([^/]+)/([^/]+)\.git]).first
end

def git_current_branch
  %x(
    BRANCH="$(git symbolic-ref -q HEAD)"
    BRANCH="${BRANCH##refs/heads/}"
    BRANCH="${BRANCH:-HEAD}"
    echo "$BRANCH"
  ).strip
end

def semaphore_project_url(*args)
  "https://semaphoreapp.com/api/v1/projects/#{project_id}/#{args.map(&:to_s).join('/')}?auth_token=#{api_token}"
end

def branch_id
  @branch_id||= begin
    @file = File.join(Dir.pwd, '.git/.morse')
    if File.exists?(@file)
      begin
        File.read(@file).lines.grep(/^#{@git_branch}:/).first[/^#{@git_branch}: (.+)/, 1]
      rescue
        find_and_cache_branch
      end
    else
      find_and_cache_branch
    end
  end
end

def find_and_cache_branch
  branch_information = JSON.parse(open(semaphore_project_url(:branches)).read)
  branch_id = (branch_information.detect { |branch| branch['name'] == @git_branch })['id']
  if !branch_id.to_s.empty?
    File.open(@file, 'a') { |file| file.write("\n#{@git_branch}: #{branch_id}") }
    branch_id
  else
    return nil
  end
end

def failed_examples
  branch_status = JSON.parse(open(semaphore_project_url(branch_id, :status)).read)
  unless branch_status['result'] == 'passed'
    log = JSON.parse(open(branch_status['build_log_url']).read)
    failing_threads_commands = []
    log['threads'].each do |thread|
      failing_threads_commands += thread['commands'].select { |command| command['result'] != '0' }
    end
    examples = []
    failing_threads_commands.each do |thread_commands|
      examples += thread_commands['output'].scan(/rspec ([^:]+:\d+)/).flatten
    end
    examples
  end
end

def run_examples(examples)
  files = examples.map { |example| example.sub(/:\d+$/, '') }.uniq
  ap "bundle exec rspec #{files.join(' ')}"
  system("bundle exec rspec #{files.join(' ')}")
end

def api_token # api_token
  @api_token ||= File.read(File.expand_path('~/.semaphore.token'))
end

def project_id # project_id
  @project_id ||= begin
    @file = File.join(Dir.pwd, '.git/.morse')
    if File.exists?(@file)
      File.read(@file).lines.grep(/^project:/).first[/^project: (.+)/, 1]
    else
      find_and_cache_project
    end
  end
end


def find_and_cache_project
  puts 'called: find_and_cache_project'
  project_details = git_current_project
  url = "https://semaphoreapp.com/api/v1/projects?auth_token=#{api_token}"
  project_info = JSON.parse open(url).read
  project_id = (project_info.detect { |pi| pi['name'] == project_details[1] && pi['owner'] == project_details[0] })['hash_id']
  if !project_id.empty?
    File.open(@file, 'a') { |file| file.write("project: #{project_id}") }
    project_id
  else
    return nil
  end
end

main
